site_name: SKIL Python Documentation
theme: readthedocs
docs_dir: sources
repo_url: https://github.com/SkymindIO/skil-python
site_url: https://skymind.ai/skil-python
site_description: 'Documentation for SKIL python client'

dev_addr: '0.0.0.0:8000'

pages:
- Home: index.md
- Getting started:
  - SKIL core concepts: core_concepts.md
  - SKIL training: training.md
  - SKIL inference: inference.md
- Basics:
  - SKIL servers: skil.md
  - Workspaces: work_space.md
  - Experiments: experiment.md
  - Models: model.md
- Training:
  - Resources: resources.md
  - Distributed training: spark.md
  - Jobs: jobs.md
- Inference:
  - Deployments: deployment.md
  - Services: service.md


